spring.application.name=administrative_service
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/barberia_db
spring.datasource.username=postgres
spring.datasource.password=eli2026
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true